name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install dependencies
        uses: nrwl/nx-set-shas@v3
        run: yarn install --frozen-lockfile

      - name: workspace-lint
        run: yarn nx workspace-lint

      - name: format
        run: yarn nx format:check

      - name: lint
        run: yarn nx affected --target=lint --parallel=3

      - name: test
        run: yarn nx affected --target=test --parallel=3 --ci --code-coverage
